export type TechLang = 'ar' | 'en' | 'hi' | 'ur';

export const techI18n: Record<TechLang, Record<string, string>> = {
  ar: {
    login: 'تسجيل الدخول',
    username: 'رقم الجوال',
    password: 'كلمة المرور',
    loginBtn: 'دخول',
    greeting: 'مرحباً',
    shiftActive: 'وردية نشطة',
    noShift: 'لم تسجل حضورك بعد',
    clockIn: 'تسجيل الحضور',
    clockOut: 'تسجيل الانصراف',
    startBreak: 'استراحة',
    endBreak: 'انهاء الاستراحة',
    onBreak: 'في استراحة',
    myTickets: 'تذاكري',
    availableTickets: 'التذاكر المتاحة',
    claimTicket: 'سحب التذكرة',
    enRoute: 'في الطريق',
    arrived: 'وصلت',
    pause: 'إيقاف مؤقت',
    resume: 'استمرار',
    complete: 'انتهيت',
    pauseReason: 'سبب الإيقاف',
    completionNotes: 'ملاحظات الإنهاء',
    clientPhone: 'رقم العميل',
    translate: 'ترجمة',
    translating: 'جاري الترجمة...',
    elapsed: 'المنقضي',
    villa: 'فيلا',
    project: 'المشروع',
    specialty: 'التخصص',
    status_CLAIMED: 'محجوزة',
    status_EN_ROUTE: 'في الطريق',
    status_IN_PROGRESS: 'جاري العمل',
    status_PAUSED: 'موقوف مؤقتاً',
    status_COMPLETED: 'مكتملة',
    profileSetup: 'إكمال ملفك الشخصي',
    fullName: 'الاسم الكامل',
    idNumber: 'رقم الهوية',
    employeeId: 'الرقم الوظيفي',
    clothingSize: 'مقاس الملابس',
    shoeSize: 'مقاس الحذاء',
    idPhoto: 'صورة الهوية',
    preferredLang: 'اللغة المفضلة',
    saveProfile: 'حفظ وتفعيل الحساب',
    hours: 'ساعات',
    minutes: 'دقائق',
    locating: 'جاري تحديد موقعك...',
    locationError: 'تعذر تحديد الموقع',
    alreadyClaimed: 'هذه التذكرة محجوزة من فني آخر',
    logout: 'خروج',
    todaySummary: 'ملخص اليوم',
    workTime: 'وقت العمل',
    breakTime: 'وقت الاستراحة',
    ticketsDone: 'تذاكر مكتملة',
  },
  en: {
    login: 'Login',
    username: 'Mobile Number',
    password: 'Password',
    loginBtn: 'Login',
    greeting: 'Welcome',
    shiftActive: 'Active Shift',
    noShift: 'You haven\'t clocked in yet',
    clockIn: 'Clock In',
    clockOut: 'Clock Out',
    startBreak: 'Start Break',
    endBreak: 'End Break',
    onBreak: 'On Break',
    myTickets: 'My Tickets',
    availableTickets: 'Available Tickets',
    claimTicket: 'Claim Ticket',
    enRoute: 'En Route',
    arrived: 'Arrived',
    pause: 'Pause',
    resume: 'Resume',
    complete: 'Complete',
    pauseReason: 'Pause Reason',
    completionNotes: 'Completion Notes',
    clientPhone: 'Client Phone',
    translate: 'Translate',
    translating: 'Translating...',
    elapsed: 'Elapsed',
    villa: 'Villa',
    project: 'Project',
    specialty: 'Specialty',
    status_CLAIMED: 'Claimed',
    status_EN_ROUTE: 'En Route',
    status_IN_PROGRESS: 'In Progress',
    status_PAUSED: 'Paused',
    status_COMPLETED: 'Completed',
    profileSetup: 'Complete Your Profile',
    fullName: 'Full Name',
    idNumber: 'ID Number',
    employeeId: 'Employee ID',
    clothingSize: 'Clothing Size',
    shoeSize: 'Shoe Size',
    idPhoto: 'ID Photo',
    preferredLang: 'Preferred Language',
    saveProfile: 'Save and Activate Account',
    hours: 'Hours',
    minutes: 'Minutes',
    locating: 'Locating...',
    locationError: 'Failed to determine location',
    alreadyClaimed: 'This ticket is claimed by another technician',
    logout: 'Logout',
    todaySummary: 'Today\'s Summary',
    workTime: 'Work Time',
    breakTime: 'Break Time',
    ticketsDone: 'Completed Tickets',
  },
  hi: {
    login: 'लॉग इन करें',
    username: 'मोबाइल नंबर',
    password: 'पासवर्ड',
    loginBtn: 'लॉग इन',
    greeting: 'नमस्ते',
    shiftActive: 'सक्रिय शिफ्ट',
    noShift: 'आपने अभी तक क्लॉक इन नहीं किया है',
    clockIn: 'क्लॉक इन',
    clockOut: 'क्लॉक आउट',
    startBreak: 'ब्रेक शुरू करें',
    endBreak: 'ब्रेक समाप्त करें',
    onBreak: 'ब्रेक पर',
    myTickets: 'मेरे टिकट',
    availableTickets: 'उपलब्ध टिकट',
    claimTicket: 'टिकट लें',
    enRoute: 'रास्ते में',
    arrived: 'पहुंच गए',
    pause: 'रोकें',
    resume: 'जारी रखें',
    complete: 'पूरा करें',
    pauseReason: 'रोकने का कारण',
    completionNotes: 'समापन नोट',
    clientPhone: 'ग्राहक का फोन',
    translate: 'अनुवाद करें',
    translating: 'अनुवाद हो रहा है...',
    elapsed: 'बीता हुआ समय',
    villa: 'विला',
    project: 'प्रोजेक्ट',
    specialty: 'विशेषज्ञता',
    status_CLAIMED: 'बुक किया गया',
    status_EN_ROUTE: 'रास्ते में',
    status_IN_PROGRESS: 'कार्य प्रगति पर है',
    status_PAUSED: 'रोका गया',
    status_COMPLETED: 'पूरा हुआ',
    profileSetup: 'अपना प्रोफाइल पूरा करें',
    fullName: 'पूरा नाम',
    idNumber: 'पहचान संख्या',
    employeeId: 'कर्मचारी आईडी',
    clothingSize: 'कपड़ों का आकार',
    shoeSize: 'जूते का आकार',
    idPhoto: 'पहचान पत्र की फोटो',
    preferredLang: 'पसंदीदा भाषा',
    saveProfile: 'सहेजें और खाता सक्रिय करें',
    hours: 'घंटे',
    minutes: 'मिनट',
    locating: 'स्थान का पता लगाया जा रहा है...',
    locationError: 'स्थान निर्धारित करने में विफल',
    alreadyClaimed: 'यह टिकट किसी अन्य तकनीशियन द्वारा लिया गया है',
    logout: 'लॉग आउट',
    todaySummary: 'आज का सारांश',
    workTime: 'काम का समय',
    breakTime: 'ब्रेक का समय',
    ticketsDone: 'पूरे किए गए टिकट',
  },
  ur: {
    login: 'لاگ ان کریں',
    username: 'موبائل نمبر',
    password: 'پاس ورڈ',
    loginBtn: 'لاگ ان',
    greeting: 'خوش آمدید',
    shiftActive: 'فعال شفٹ',
    noShift: 'آپ نے ابھی تک کلاک ان نہیں کیا',
    clockIn: 'کلاک ان',
    clockOut: 'کلاک آؤٹ',
    startBreak: 'وقفہ شروع کریں',
    endBreak: 'وقفہ ختم کریں',
    onBreak: 'وقفے پر',
    myTickets: 'میرے ٹکٹ',
    availableTickets: 'دستیاب ٹکٹ',
    claimTicket: 'ٹکٹ حاصل کریں',
    enRoute: 'راستے میں',
    arrived: 'پہنچ گیا',
    pause: 'روکیں',
    resume: 'جاری رکھیں',
    complete: 'مکمل کریں',
    pauseReason: 'روکنے کی وجہ',
    completionNotes: 'تکمیل کے نوٹس',
    clientPhone: 'کلائنٹ کا فون',
    translate: 'ترجمہ کریں',
    translating: 'ترجمہ ہو رہا ہے...',
    elapsed: 'گزرا ہوا وقت',
    villa: 'ولا',
    project: 'پروجیکٹ',
    specialty: 'مہارت',
    status_CLAIMED: 'بک کیا گیا',
    status_EN_ROUTE: 'راستے میں',
    status_IN_PROGRESS: 'کام جاری ہے',
    status_PAUSED: 'روک دیا گیا',
    status_COMPLETED: 'مکمل ہو گیا',
    profileSetup: 'اپنی پروفائل مکمل کریں',
    fullName: 'پورا نام',
    idNumber: 'شناختی نمبر',
    employeeId: 'ملازم کی آئی ڈی',
    clothingSize: 'کپڑوں کا سائز',
    shoeSize: 'جوتے کا سائز',
    idPhoto: 'شناختی کارڈ کی تصویر',
    preferredLang: 'پسندیدہ زبان',
    saveProfile: 'محفوظ کریں اور اکاؤنٹ فعال کریں',
    hours: 'گھنٹے',
    minutes: 'منٹ',
    locating: 'مقام تلاش کیا جا رہا ہے...',
    locationError: 'مقام کا تعین کرنے میں ناکام',
    alreadyClaimed: 'یہ ٹکٹ کسی دوسرے ٹیکنیشن نے حاصل کر لیا ہے',
    logout: 'لاگ آؤٹ',
    todaySummary: 'آج کا خلاصہ',
    workTime: 'کام کا وقت',
    breakTime: 'وقفے کا وقت',
    ticketsDone: 'مکمل شدہ ٹکٹ',
  },
};

export function t(lang: TechLang, key: string): string {
  return techI18n[lang]?.[key] || techI18n['ar'][key] || key;
}
